spring:
  application:
    name: eureka-client-user-service-app

  cloud:
    discovery:
      client:
        simple:
          instance:
            prefer-ip-address: true

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost
        prefer-ip-address: true

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - env
          - metrics
        exclude:
          - shutdown

  endpoint:
    health:
      show-details: always
